/*
 * Copyright 2018 NXP. 
 * This software is owned or controlled by NXP and may only be used strictly in accordance with the
 * license terms that accompany it. By expressly accepting such terms or by downloading, installing,
 * activating and/or otherwise using the software, you are agreeing that you have read, and that you
 * agree to comply with and are bound by, such license terms. If you do not agree to be bound by the
 * applicable license terms, then you may not retain, install, activate or otherwise use the software.
 */

#ifndef _SLN_FILE_TABLE_
#define _SLN_FILE_TABLE_

#include "sln_flash_mgmt.h"
#include "sln_dev_cfg.h"

/*! Addresses for files */

#define SLN_FLASH_TBL_RES               RESERVED
#define SLN_FLASH_TBL_STR(x)            #x
#define SLN_FLASH_TBL_PRINT(x)          SLN_FLASH_TBL_STR(x)
#define SLN_FLASH_TBL_CAT_OUT(a, b)     a##b
#define SLN_FLASH_TBL_CAT(a, b)         SLN_FLASH_TBL_CAT_OUT(a, b)

#define SLN_FLASH_INDEX                 0

#define SLN_FLASH_ENTRY(name, index, encrypt) { name, SLN_FLASH_MGMT_FILE_ADDR(index), encrypt }

const sln_flash_entry_t g_fileTable[] =
{

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 1

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 2

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 3

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 4

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 5

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 6

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 7

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 8

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 9

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 10

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 11

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 12

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 13

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 14

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 15

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

        // Start of NXP defined files; DO NOT edit below if using NXP kit & eco-system

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 16

#ifdef CONFIG_DATA_FILE_NAME
        SLN_FLASH_ENTRY(CONFIG_DATA_FILE_NAME, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 17

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 18

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 19

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 20

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 21

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 22

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 23

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 24

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 25

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 26

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 27

        SLN_FLASH_ENTRY( SLN_FLASH_TBL_PRINT( SLN_FLASH_TBL_CAT( SLN_FLASH_TBL_RES, SLN_FLASH_INDEX ) ), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

        // End of NXP defined files

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 28

        SLN_FLASH_ENTRY("", 0, 0)

};

#endif /* _SLN_FILE_TABLE_ */
